/****** Script for SelectTopNRows command from SSMS  ******/
--SELECT TOP (1000) [TimeStamp]
--      ,[JobId]
--      ,[SchedulingIntervalInSecs]
--      ,[VCId]
--      ,[AUId]
--      ,[JobStateId]
--      ,[Priority]
--      ,[TokenAllocation]
--      ,[TotalWaitingTimeInMins]
--      ,[TotalYieldTimeInMins]
--      ,[TotalRunningTimeInMins]
--      ,[EstimatedRemainingRunningTimeInMins]
--      ,[VertexProgress]
  SELECT TOP (1000) [TimeStamp]
      ,[JobId]
      ,[SchedulingIntervalInSecs]
      ,[VCId]
      ,[AUId]
      ,[JobStateId]
      ,[Priority]
      ,[TokenAllocation]
      ,[TotalWaitingTimeInMins]
      ,[TotalYieldTimeInMins]
      ,[TotalRunningTimeInMins]
      ,[EstimatedRemainingRunningTimeInMins]
      ,[VertexProgress]
  FROM [JobScheduling].[dbo].[JobSnapshot]
  WHERE TimeStamp >'2021-07-20'and TimeStamp<'2021-07-27'